run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Reports suspicious constructs
    - ineffassign   # Detects ineffectual assignments
    - staticcheck   # Staticcheck is a go vet on steroids
    - unused        # Checks for unused constants, variables, functions and types
    - gofmt         # Checks whether code was gofmt-ed
    - goimports     # Checks import statements are formatted correctly
    - misspell      # Finds commonly misspelled English words
    - revive        # Fast, configurable, extensible, flexible linter
    - gosec         # Security problems (important for pentest tool)
    - bodyclose     # Checks whether HTTP response body is closed
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Reports unused function parameters

  disable:
    - typecheck     # Can be redundant with gopls

linters-settings:
  errcheck:
    check-blank: false
    check-type-assertions: false

  govet:
    enable-all: true
    disable:
      - shadow      # Too strict for this codebase
      - fieldalignment  # Micro-optimization not needed

  revive:
    confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
        disabled: true  # Not enforcing package comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code

  gosec:
    # Security is important for pentesting tools
    # But some checks need to be relaxed for this type of tool
    excludes:
      - G204  # Subprocess launched with variable - expected in pentesting tool
      - G304  # File path provided as taint input - expected behavior
      - G301  # Poor file permissions - may be intentional
    confidence: medium
    severity: medium

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/0x5ubt13/enumeraga

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - unparam

    # Allow globals in utils package (common pattern)
    - path: internal/utils/
      text: "global variable"

    # Allow command execution in commands package (that's the purpose)
    - path: internal/commands/
      linters:
        - gosec
      text: "G204"

  exclude:
    # Ignore "should have comment" warnings for now
    - "comment on exported"
    # Allow long functions in main and setup code
    - "Function 'main' is too long"
    - "cyclomatic complexity"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
