version: "2"
run:
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - gosec
    - misspell
    - revive
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gosec:
      excludes:
        - G104
        - G107
        - G110
        - G204
        - G304
        - G305
        - G301
        - G302
        - G306
    govet:
      enable:
        - printf
        - stdmethods
        - unmarshal
      disable:
        - shadow
        - fieldalignment
      enable-all: false
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
          disabled: true
        - name: increment-decrement
          disabled: true
        - name: var-naming
          disabled: true
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: indent-error-flow
          disabled: true
        - name: superfluous-else
          disabled: true
        - name: unreachable-code
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
      - path: internal/utils/
        text: (global variable|G101)
      - linters:
          - gosec
        path: internal/(commands|portsIterator|scans)/
        text: G204
      - linters:
          - gosec
        path: internal/infra/
        text: G30[1246]
      - linters:
          - staticcheck
        text: 'SA1019:'
      - path: (.+)\.go$
        text: should have( a package)? comment
      - path: (.+)\.go$
        text: comment on exported
      - path: (.+)\.go$
        text: do not define dynamic errors
      - path: (.+)\.go$
        text: File is not `gofmt`-ed
      - path: (.+)\.go$
        text: File is not `goimports`-ed
      - path: (.+)\.go$
        text: cyclomatic complexity
      - path: (.+)\.go$
        text: cognitive complexity
      - path: (.+)\.go$
        text: Function .* is too long
      - path: (.+)\.go$
        text: 'G104: Errors unhandled'
      - path: (.+)\.go$
        text: weak cryptographic primitive
      - path: (.+)\.go$
        text: response body must be closed
      - path: (.+)\.go$
        text: declaration of .* shadows
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 3
formatters:
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/0x5ubt13/enumeraga
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
